FROM alpine:latest

COPY requirements* /
COPY project/staff/requirements.txt /staff/requirements.txt

RUN echo "http://mirror.leaseweb.com/alpine/edge/community" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    echo "**** install Python ****" && \
    apk add --no-cache python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    \
    echo "**** install pip ****" && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    apk add --no-cache mariadb-dev libev-dev jpeg-dev zlib-dev libxml2-dev libxslt-dev postgresql-dev && \
    apk add --no-cache --virtual .build-deps gcc g++ musl-dev libffi-dev libc-dev linux-headers python3-dev && \
    pip install --no-cache-dir  pip install lxml pillow && \
    apk add --virtual .build-deps-temp \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
        geos-dev geos && \
        runDeps="$(scanelf --needed --nobanner --recursive /usr/local \
        | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
        | xargs -r apk info --installed \
        | sort -u)" && \
    apk add --virtual .rundeps $runDeps && \
    pip install --no-cache-dir -r /requirements-bjoern.txt && \
    pip install --no-cache-dir -r /requirements-static_server.txt && \
    pip install --no-cache-dir -r /requirements-db-mysql.txt && \
    pip install --no-cache-dir -r /staff/requirements.txt && \
    apk del .build-deps && \
    rm -Rf ~/.cache
